"""Add passport_serial to teacher

Revision ID: 5eef9e0b9a0c
Revises: b9ea07b596ad
Create Date: 2026-01-15 14:35:56.088548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eef9e0b9a0c'
down_revision: Union[str, Sequence[str], None] = 'b9ea07b596ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('passport_serial', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'teachers', ['passport_serial'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_column('teachers', 'passport_serial')
    # ### end Alembic commands ###
