"""add_subjects_and_test_relation

Revision ID: 8aa19c36ceb6
Revises: 5eef9e0b9a0c
Create Date: 2026-01-15 14:52:29.798873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa19c36ceb6'
down_revision: Union[str, Sequence[str], None] = '5eef9e0b9a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tests', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_column('tests', 'subject_id')
    # ### end Alembic commands ###
