"""Add jshshir to teacher

Revision ID: b9ea07b596ad
Revises: 17d708a30514
Create Date: 2026-01-15 14:26:02.725787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ea07b596ad'
down_revision: Union[str, Sequence[str], None] = '17d708a30514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('jshshir', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'jshshir')
    # ### end Alembic commands ###
